
require('dotenv').config();
module.exports =
    {
        "development": {
            "ARROWAPI_MONGO_HOST_URL": process.env.ARROWAPI_MONGO_HOST_URL,
            "ARROWAPI_MONGO_USER": process.env.ARROWAPI_MONGO_USER ,
            "ARROWAPI_MONGO_PASSWORD": process.env.ARROWAPI_MONGO_PASSWORD,
            "ARROWAPI_COSMO_HOST_URL": process.env.ARROWAPI_COSMO_HOST_URL,
            "ARROWAPI_COSMO_USER": process.env.ARROWAPI_COSMO_USER,
            "ARROWAPI_COSMO_PASSWORD": process.env.ARROWAPI_COSMO_PASSWORD,
            "ARROWAPI_REDIS_HOST_URL": process.env.ARROWAPI_REDIS_HOST_URL,
            "ARROWAPI_REDIS_HOST_PORT": process.env.ARROWAPI_REDIS_HOST_PORT,
            "ARROWAPI_REDIS_HOST_PASSWORD": process.env.ARROWAPI_REDIS_HOST_PASSWORD,
            "ARROWAPI_MYSQL_HOST_URL": process.env.ARROWAPI_MYSQL_HOST_URL,
            "ARROWAPI_MYSQL_PORT": process.env.ARROWAPI_MYSQL_PORT,
            "ARROWAPI_MYSQL_DATABASE": process.env.ARROWAPI_MYSQL_DATABASE,
            "ARROWAPI_MYSQL_USER": process.env.ARROWAPI_MYSQL_USER,
            "ARROWAPI_MYSQL_PASSWORD": process.env.ARROWAPI_MYSQL_PASSWORD,

        },
        "staging": {
            "ARROWAPI_MONGO_HOST_URL": process.env.ARROWAPI_MONGO_HOST_URL,
            "ARROWAPI_MONGO_USER": process.env.ARROWAPI_MONGO_USER ,
            "ARROWAPI_MONGO_PASSWORD": process.env.ARROWAPI_MONGO_PASSWORD,
            "ARROWAPI_COSMO_HOST_URL": process.env.ARROWAPI_COSMO_HOST_URL,
            "ARROWAPI_COSMO_USER": process.env.ARROWAPI_COSMO_USER,
            "ARROWAPI_COSMO_PASSWORD": process.env.ARROWAPI_COSMO_PASSWORD,
            "ARROWAPI_REDIS_HOST_URL": process.env.ARROWAPI_REDIS_HOST_URL,
            "ARROWAPI_REDIS_HOST_PORT": process.env.ARROWAPI_REDIS_HOST_PORT,
            "ARROWAPI_REDIS_HOST_PASSWORD": process.env.ARROWAPI_REDIS_HOST_PASSWORD,
            "ARROWAPI_MYSQL_HOST_URL": process.env.ARROWAPI_MYSQL_HOST_URL,
            "ARROWAPI_MYSQL_PORT": process.env.ARROWAPI_MYSQL_PORT,
            "ARROWAPI_MYSQL_DATABASE": process.env.ARROWAPI_MYSQL_DATABASE,
            "ARROWAPI_MYSQL_USER": process.env.ARROWAPI_MYSQL_USER,
            "ARROWAPI_MYSQL_PASSWORD": process.env.ARROWAPI_MYSQL_PASSWORD,


        },
        "production": {
            "ARROWAPI_MONGO_HOST_URL": process.env.ARROWAPI_MONGO_HOST_URL,
            "ARROWAPI_MONGO_USER": process.env.ARROWAPI_MONGO_USER ,
            "ARROWAPI_MONGO_PASSWORD": process.env.ARROWAPI_MONGO_PASSWORD,
            "ARROWAPI_COSMO_HOST_URL": process.env.ARROWAPI_COSMO_HOST_URL,
            "ARROWAPI_COSMO_USER": process.env.ARROWAPI_COSMO_USER,
            "ARROWAPI_COSMO_PASSWORD": process.env.ARROWAPI_COSMO_PASSWORD,
            "ARROWAPI_REDIS_HOST_URL": process.env.ARROWAPI_REDIS_HOST_URL,
            "ARROWAPI_REDIS_HOST_PORT": process.env.ARROWAPI_REDIS_HOST_PORT,
            "ARROWAPI_REDIS_HOST_PASSWORD": process.env.ARROWAPI_REDIS_HOST_PASSWORD,
            "ARROWAPI_MYSQL_HOST_URL": process.env.ARROWAPI_MYSQL_HOST_URL,
            "ARROWAPI_MYSQL_PORT": process.env.ARROWAPI_MYSQL_PORT,
            "ARROWAPI_MYSQL_DATABASE": process.env.ARROWAPI_MYSQL_DATABASE,
            "ARROWAPI_MYSQL_USER": process.env.ARROWAPI_MYSQL_USER,
            "ARROWAPI_MYSQL_PASSWORD": process.env.ARROWAPI_MYSQL_PASSWORD,

        }
    }
